// Generated by scripts/generate_runtime_config.js
window.__API_BASE__ = "";
window.__RPC_URL__ = "https://ethereum-sepolia-rpc.publicnode.com";
window.__CHAIN_ID__ = "11155111";
window.__VOTING_ADDRESS__ = "";
