const fs = require('fs');
const path = require('path');

require('dotenv').config();

const outputPath = path.join(__dirname, '..', 'src', 'js', 'runtime-config.js');

const runtimeConfig = {
  apiBase: String(process.env.FRONTEND_API_BASE || '').trim(),
  rpcUrl: String(process.env.RPC_URL || 'https://ethereum-sepolia-rpc.publicnode.com').trim(),
  chainId: String(process.env.CHAIN_ID || '11155111').trim(),
  votingAddress: String(process.env.VOTING_CONTRACT_ADDRESS || '').trim(),
};

const fileContents = [
  '// Generated by scripts/generate_runtime_config.js',
  `window.__API_BASE__ = ${JSON.stringify(runtimeConfig.apiBase)};`,
  `window.__RPC_URL__ = ${JSON.stringify(runtimeConfig.rpcUrl)};`,
  `window.__CHAIN_ID__ = ${JSON.stringify(runtimeConfig.chainId)};`,
  `window.__VOTING_ADDRESS__ = ${JSON.stringify(runtimeConfig.votingAddress)};`,
  '',
].join('\n');

fs.writeFileSync(outputPath, fileContents, 'utf8');

console.log(`Wrote runtime config to ${outputPath}`);
